### ISSUE TITLE
Question: base node restart requires restart of every service?

### ISSUE THREAD

**Issue by blanchma** [rjrodger/seneca-mesh#35]
I have a node-base which is actually an API Gateway. If in any time this node-base goes down, do I have to restart every node-service? Is there anyway to ask the node-service to search for a base again?

**Comment by rjrodger** [comment]
No you should not have to - base nodes are only a convenience to join the network.
They simply serve as well known network locations.

It's better to have a separate set of base nodes, as you are separating concerns.

**Comment by behrad** [comment]
@rjrodger I have a simple mesh setup [here](https://github.com/behrad/seneca-test) on which 
1. when base node is killed, client is unable to reach the service node
2. when base node is restarted, service node should be restarted afterwards, so that client can see the service!

Can you help me to figure out if this is a miss configuration or a miss-behavior?

**Comment by blanchma** [comment]
When a base node is killed, the clients that has already joined the mesh doesn't require to be in contact with the base node. The base node is required only initially when a client/service is started.

If this is not working for you, it probably means a miss configuration. Share with us your configs.

**Comment by behrad** [comment]
> @rjrodger I have a simple mesh setup here on which

Would you please check out [the sample code](https://github.com/behrad/seneca-test) @blanchma ?

**Comment by danielo515** [comment]
My experience taught me that restarting base nodes requires a restart of all the services on the mesh.
This is a big problem for me, because it means that every time I have to make a change to the bases I have to restart the entire network.
